image: ekidd/rust-musl-builder:stable-openssl11

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/

stages:
  - test
  - build

test:
  stage: test
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y python3 python3-pip
    - python3.6 -m pip install --user -r requirements.txt
  script:
    - rustc --version && cargo --version
    - cargo build --all
    - cargo test --all --verbose

x86_64-unknown-linux-musl:
  stage: build

  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/gerritbot

  script:
    - cargo build --release --target x86_64-unknown-linux-musl
